### ISSUE TITLE
Kodi 19 Matrix support

### ISSUE THREAD

**Issue by i3laze** [nickjwhite/Kodi.Script.ToggleLGTVPower#1]
As Python 2.7 support is dropped in modern Kodi 19... 
Any chance you could rewrite the original script AND plugin to Python 3 to support latest Kodi? (I used both)
https://github.com/BillyNate/Kodi.Script.TurnOffLGTV

There's bunch of online tools for that in case:
https://python2to3.com/

**Comment by nickjwhite** [comment]
Yeah, I saw that recently when I updated my Kodi. Sure, I'll have a 
look and try to find the time to update this and the TurnOffLGTV 
plugin to work with modern Kodi, thanks for the interest.

**Comment by nickjwhite** [comment]
Alright, I've had a stab at it, and things seem to be working.

For this addon, I just committed the fix as 5145d73, and tagged it as a new version, v0.3.0.

I also opened a pull request for the Kodi.Script.TurnOffLGTV repository with the change https://github.com/BillyNate/Kodi.Script.TurnOffLGTV/pull/1 - in the meantime you can use my version at https://github.com/nickjwhite/Kodi.Script.TurnOffLGTV

Please do test it; I changed to using OSMC recently, and the cec-client seems to perform differently there, so I can only get the turning the TV on working reliably, not off. But I suspect that's more to do with OSMC's cec-client than the addon. Thanks for prompting me to do this, I probably wouldn't have ever gotten around to it unless you had ;)

**Comment by i3laze** [comment]
Thanks!
As an owner of 2014 LG I can just say:
“You’re my only hope”.

Will give it a try in a day or two.

**Comment by i3laze** [comment]
Ehm.. didn't work.

`2022-02-18 16:25:47.265 T:6206     INFO <general>: initializing python engine.
2022-02-18 16:25:47.959 T:6206    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'urllib' has no attribute 'Request'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 395, in <module>
                                                       networkShutdownScreensaver = LGTVNetworkShutdownScreensaver()
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 73, in __init__
                                                       self.cli = LGTVNetworkShutdown2012(ip_address)
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 239, in __init__
                                                       if self.check_registration(ip_address) == True:
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 188, in check_registration
                                                       request = urllib.Request('http://'+ip_address+':8080/roap/api/auth',data=data,headers=self.HTTP_HEADERS)
                                                   AttributeError: module 'urllib' has no attribute 'Request'
                                                   -->End of Python script error report<--

2022-02-18 16:25:47.959 T:6206     INFO <general>: CPythonInvoker(15, /storage/.kodi/addons/kodi.script.turnofflgtv/addon.py): waiting on thread 3828343424
2022-02-18 16:25:58.959 T:6206     INFO <general>: Python interpreter stopped

`

**Comment by i3laze** [comment]
Sorry, didn't work on Kodi Matrix (CoreElec 19.4rc2)..
```
2022-02-18 16:38:39.390 T:8199     INFO <general>: initializing python engine.
2022-02-18 16:38:40.041 T:8199    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'urllib' has no attribute 'Request'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 395, in <module>
                                                       networkShutdownScreensaver = LGTVNetworkShutdownScreensaver()
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 73, in __init__
                                                       self.cli = LGTVNetworkShutdown2012(ip_address)
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 239, in __init__
                                                       if self.check_registration(ip_address) == True:
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 188, in check_registration
                                                       request = urllib.Request('http://'+ip_address+':8080/roap/api/auth',data=data,headers=self.HTTP_HEADERS)
                                                   AttributeError: module 'urllib' has no attribute 'Request'
                                                   -->End of Python script error report<--

2022-02-18 16:38:40.042 T:8199     INFO <general>: CPythonInvoker(19, /storage/.kodi/addons/kodi.script.turnofflgtv/addon.py): waiting on thread 3744449152
2022-02-18 16:38:51.130 T:8199     INFO <general>: Python interpreter stopped
```

I've changed lines 188 and 224 to urllib.request.Request..  digging deeper.

**Comment by nickjwhite** [comment]
Oh, good spot, I wonder why it didn't give me that error. Hopefully with those 2 changes it all works - please test and let me know!

**Comment by i3laze** [comment]
There's a tremendous pain to send an XML using POST method via urllib2 in Python3 : (
Seems it should be encoded in bytes.. 
https://docs.python.org/3/howto/urllib2.html
https://docs.python.org/3/library/urllib.request.html#urllib.request.Request

I'm not a developer..
Please investigate this in your spare time.

**Comment by nickjwhite** [comment]
Well, it may be suboptimal, but I'm not much of a Python developer either; I know enough to fix this up, but I'm afraid I'm not invested enough in making it better, beyond "this works as well as it did before" - sorry ;) You could open a bug report on the BillyNate repo.

**Comment by i3laze** [comment]
Can’t POST XML data yet.
No problem, thanks for trying.

**Comment by nickjwhite** [comment]
Oh wait, I think I was misunderstanding your previous comment - I thought you were complaining about the code quality in general!

Do you mean that there's a new error, encoding the XML for the Post? If so, paste the error here and I can probably fix it. As I said, for some reason it's working for me, so your help is much appreciated! :)

**Comment by i3laze** [comment]
Yeap, after modifying line 188 with urllib.request.Request:
As mentioned, seems XML _string_ is not accepted by urllib2 for POST data.
```
2022-02-18 21:18:10.318 T:3724    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 395, in <module>
                                                       networkShutdownScreensaver = LGTVNetworkShutdownScreensaver()
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 73, in __init__
                                                       self.cli = LGTVNetworkShutdown2012(ip_address)
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 239, in __init__
                                                       if self.check_registration(ip_address) == True:
                                                     File "/storage/.kodi/addons/kodi.script.turnofflgtv/addon.py", line 189, in check_registration
                                                       response = urllib.request.urlopen(request, timeout=self.HTTP_TIMEOUT)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                     File "/usr/lib/python3.8/urllib/request.py", line 522, in open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1285, in do_request_
                                                   TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
                                                   -->End of Python script error report<--
```
